# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-08 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cubierta_1040842',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region97', models.IntegerField()),
                ('reg07', models.IntegerField()),
            ],
            options={
                'db_table': 'cubierta_1040842',
            },
        ),
    ]
